### ISSUE TITLE
TrimmedDataAccessException 

### ISSUE THREAD

**Issue by Ohadbasan** [ironSource/node-dynamodb-stream#13]
I am getting a ExpiredIteratorException exception on subsequent calls to fetchStreamRecords:

TrimmedDataAccessException: The data you are trying to access has been trimmed

since we obtain the "LATEST" on each  shard iterator get request the problem is probably this (https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetShardIterator.html)

`You obtain a shard iterator, but before you use the iterator in a GetRecords request, a stream record in the shard exceeds the 24 hour period and is trimmed. This causes the iterator to access a record that no longer exists.`

current tests will not cover this scenario (we'll need a dynamo mock for that) but I think that the solution is in _getShardRecords:

we need to nullify the nextShardIterator as long as the nextShardIterator in the getRecords result is not null. regardless of whether we got new records or not.
not sure though.

**Comment by kessler** [comment]
fixed in https://github.com/ironSource/node-dynamodb-stream/commit/7b5e2deb47ae6dd45e003769b9f16a1e117f5f92
