### ISSUE TITLE
Raw stream event

### ISSUE THREAD

**Issue by abhayachauhan** [ironSource/node-dynamodb-stream#4]
First off, love the module, great stuff! Encapsulates the complexity around DynamoDb stream really well.

My use case, is to leverage this package to imitate Lambda in regions where Lambda has yet to be released. Eg: Sydney, Singapore. Trigger a module based on Dynamo Stream changes.

In Lambda, the raw event from the stream is passed to the function (including table name, new version, old version, etc).
It would be great to leverage dynamodb stream polling, and pass the raw event back.
Ie - 
```
var params = { rawEvent = true; }
dbStream.fetchStreamState(params, callback);

```

Thoughts?
It would be a great option for leverage, if you are interested in this feature. Happy to provide a PR if so.

**Comment by kessler** [comment]
Hey, Sorry for the delayed response. I'm not sure I understand the use case, what is ```rawEvent = true``` suppose to do ?

**Comment by kessler** [comment]
@abhayachauhan see recent merged PRs
