### ISSUE TITLE
Doesn't provide any data for key only streams

### ISSUE THREAD

**Issue by simonbooth** [ironSource/node-dynamodb-stream#9]
For larger datasets it is better to only get the data you are interested in, so you might want to use a keys only view.

**Comment by kessler** [comment]
closed accidentally

**Comment by kessler** [comment]
my commit [here](https://github.com/ironSource/node-dynamodb-stream/commit/7b5e2deb47ae6dd45e003769b9f16a1e117f5f92) wrongfully closes this issue
